name: Vulnerability Check

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"

jobs:
  govulncheck-check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
          check-latest: true
          cache: false

      - name: Install Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Run Govulncheck
        run: govulncheck ./...
